### ISSUE TITLE
DOS vs UTF-8

### ISSUE THREAD

**Issue by zvezdochiot** [vmarkovtsev/fresheye#1]
Почему под CP866? С UTF-8 наверняка проблемы (другая длина символа), но всё же? Добавить внутренний перекодировшик UTF-8 -> DOS => FE => DOS -> UTF-8?

PS: За адаптацию всё равно спасибо.

**Comment by vmarkovtsev** [comment]
Так ведь заголовок: "Быстрая адаптация" :smile: Сделано на коленке за пару часов и зингер из KFC. PRs welcome!

**Comment by zvezdochiot** [comment]
Понятно. Хорошая тулза. Правда выпала из поля зрения и забылась. Только сейчас наткнулся и давай шарить по git-у. Хорошая тулза. Правильная. Спасибо.
